name: Azure App Service CI/CD

on:
  push:
    branches:
      - main  # Altere para o nome da branch usada no seu repositório, se for diferente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Arquivo de inicialização do App
      run: echo "web: gunicorn app:app" > Procfile

    - name: Deploy para Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: libcredit-app  # 🔁 Substitua pelo nome exato do seu App Service
        slot-name: production
        publish-profile: https://github.com/herick-ferreira/app-libcredito-pucpr

