version: '3.8'

services:
  web:
    build: .
    container_name: app-libcredito-pucpr
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`)"
      - "traefik.http.services.app.loadbalancer.server.port=8000"

networks:
  default:
    name: app-network
